platform :ios, '9.0'

use_frameworks!

target "SpryExample" do
    pod 'Nimble'
    pod 'Spry', :path => './../'
    pod 'Spry+Nimble', :path => './../'

    target 'SpryExampleTests' do
        inherit! :search_paths

        pod 'Quick'
    end
end
